### PR TITLE
Updated to Promise@6.1.0, removed improved-denodeify.js

### PR DESCRIPTION
**Pull request by ArtskydJ**
The tests pass.

### CODE REVIEW

**Comment by TehShrike** [comment]
Awesome!

**Comment by TehShrike** [comment]
If I was an official contributor to the project, I would totally merge this right now :-)

**Comment by ArtskydJ** [comment]
_Hint, hint_ @saibotsivad. :smile:

**Comment by saibotsivad** [comment]
Awwwww yisssss!!!!

**Comment by saibotsivad** [comment]
@TehShrike @ArtskydJ [Boom!](https://github.com/orgs/sdmp/teams/making-modules) You both are contributors! (I think. Let me know if those aren't the right settings.) Please follow the [OPEN open source contributing guidelines](https://github.com/rvagg/node-levelup/blob/master/CONTRIBUTING.md).

**Pull request merged**
